# --------------------------------------------------------------  
# (C)Copyright 2001,2006,                                         
# International Business Machines Corporation,                    
# Sony Computer Entertainment, Incorporated,                      
# Toshiba Corporation,                                            
#                                                                 
# All Rights Reserved.                                            
# --------------------------------------------------------------  
# PROLOG END TAG zYx                                              

########################################################################
#			Target
########################################################################

PROGRAMS_spu := rc5_encrypt rc5_decrypt

LIBRARY_embed := rc5_encrypt.a rc5_decrypt.a
#CFLAGS = -DPROFILING

########################################################################
#			Local Defines
########################################################################



########################################################################
#			make.footer
########################################################################

include ../make.defs
include $(MAKE_FOOTER)

